name: main

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Ubuntu Ubuntu
      if: matrix.os == 'ubuntu-latest'
    - run: sudo apt update -y
    - name: Ubuntu Install
      if: matrix.os == 'ubuntu-latest'
    - run: sudo apt install cmake make g++ -y
    - name: Ubuntu build
      if: matrix.os == 'ubuntu-latest'
    - run: |
        mkdir build && cd build
        cmake .. && make      